[window]
padding = { x = 10, y = 0 }

[font]
size = 16

[font.normal]
family = "Hack Nerd Font"

[mouse]
hide_when_typing = true

[cursor]
blink_timeout = 0

[colors.primary]
background = '#161618'
foreground = '#afb8b8'

[colors.cursor]
text   = '#161618'
cursor = '#afb8b8'

[colors.selection]
text       = '#161618'
background = '#616e88'

[colors.normal]
black   = '#534c50'
red     = '#bf616a'
green   = '#678e87'
yellow  = '#ebcb8b'
blue    = '#da9d38'
magenta = '#c7a2aa'
cyan    = '#8ca4c8'
white   = '#afb8b8'

[[keyboard.bindings]]
key = "Space"
mods = "Shift"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
