padding_width 10
padding_height 10
font_family Hack Nerd Font
font_size 16
mouse_hide_wait 1
hide_mouse_when_typing yes
cursor_shape block
shell_integration no-cursor
cursor_stop_blinking_after 0
enable_audio_bell no

# Colors
background #161618
foreground #afb8b8
cursor #afb8b8
cursor_text_color #161618
selection_background #616e88
selection_foreground #161618

color0  #534c50
color1  #bf616a
color2  #678e87
color3  #ebcb8b
color4  #da9d38
color5  #c7a2aa
color6  #8ca4c8
color7  #afb8b8

# Tabs
tab_bar_edge top
tab_bar_style separator
tab_separator " "
tab_bar_background none
tab_bar_min_tabs 1
tab_title_template "{index}:{tab.active_exe}"

active_tab_background   #161618
inactive_tab_background #161618
active_tab_foreground   #afb8b8
inactive_tab_foreground #534c50
active_tab_font_style   bold
inactive_tab_font_style normal

# Keybinds
map ctrl+shift+t new_tab
map ctrl+shift+c close_tab

map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9
